### PR TITLE
Extract MasterOperations and additional info in OutputToCSV.m

### PR DESCRIPTION
**Pull request by imraniac**
Also made necessary changes in TS_LoadData.m

### CODE REVIEW

**Comment by benfulcher** [comment]
@imraniac I've made some edits to use `writetable` commands. I think the `MasterOperations` can be loaded as normal (rather than incorporated into `TS_LoadData`). Can you check that my edits word…?

**Comment by benfulcher** [comment]
They work from my tests, so I'll merge for now :) Thanks for the contribution!

**Comment by imraniac** [comment]
@benfulcher I m currently using Matlab 2017 version so it throws an error
`Undefined function or variable 'removevars'` in OutputToCSV

**Comment by benfulcher** [comment]
@imraniac Are you able to find a way to remove the Data column from the TimeSeries table in the old syntax? Then you can split using an `if` statement on the `version` command (i.e., if an older version of Matlab)

**Comment by benfulcher** [comment]
Would be great to incorporate these few lines for back-compatability

**Pull request merged**
